[package]
name = "genai"
version = "0.0.13-alpha.1"
edition = "2021"
rust-version = "1.78"
license = "MIT OR Apache-2.0"
description = "Multi-Provider Generative AI Rust Library. (Ollama, OpenAI, Gemini, Anthropic, Cohere, ...)"
keywords = [
	"generative-ai",
	"library",
	"openai",
	"Ollama",
	"ollama"
]
homepage = "https://github.com/jeremychone/rust-genai"
repository = "https://github.com/jeremychone/rust-genai"

[lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.

[dependencies]
# -- Async
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
tokio-stream = "0.1"
# -- Json
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = { version = "3", features = ["macros"] }
# -- Web
reqwest = {version = "0.12", features = ["json"]}
reqwest-eventsource = "0.6"
eventsource-stream = "0.2"
bytes = "1.6"
# -- Others
derive_more = { version = "1.0.0-beta", features = ["from", "display"] }
